### ISSUE TITLE
Failure to Discover Squeezebox Boom

### ISSUE THREAD

**Issue by meichthys** [home-assistant-libs/aioslimproto#50]
When running the example script i receive the following:
```
2022-07-11 00:34:27,782 ERROR aioslimproto.discovery -- Error occured while trying to parse a datagram from ('192.168.0.111', 3483) - data: b'd\x00\n9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04 \x1e\xa7\\'
Traceback (most recent call last):
  File "/Users/noname/aioslimproto/aioslimproto/discovery.py", line 203, in datagram_received
    dgram = Datagram.decode(data)
  File "/Users/noname/aioslimproto/aioslimproto/discovery.py", line 42, in decode
    return ClientDiscoveryDatagram(data)
  File "/Users/noname/aioslimproto/aioslimproto/discovery.py", line 62, in __init__
    msg = struct.unpack("!cxBB8x6B", data.encode())
struct.error: unpack requires a buffer of 18 bytes
```

**Comment by marcelveldt** [comment]
1) The example script is there for development reasons only and not a real world application.

2) Did you test with latest version as I checked in a few changes last week.

3) I have some more reports of some "real" Squeezebox hardware not working, I'm looking into that but a bit difficult because my last real squeezebox died and now I only have alternative hardware.

**Comment by meichthys** [comment]
I'm not sure if your latest changes are in Homeassistant core yet. If they are, then yes I have tested them, otherwise, no.

**Comment by meichthys** [comment]
Just for reference, I've re-tested in HA 2022.8.2 and still cant seem to get the boom to be discovered.

**Comment by marcelveldt** [comment]
Unfortunately a lot more work is needed to get the "real" squeezebox hardware working (or anyway at least the Radio and the Boom are reported).  My last real squeezebox Radio died so this is a bit tricky for me to debug but I discovered that the squeezeplay software client (not squeezelite) behaves just like a squeezebox touch and also does not get past the first discovery round. First finding is that it fails due to the lack of display support.

I'll do my best to give this another shot coming week now that I can test with the squeezeplay software.

**Comment by jkasten80** [comment]
Any news here?

**Comment by marcelveldt** [comment]
Sorry, no green light yet but I made some progress. I'll give you an update within a week. Hopefully with at least a timeframe to finish it or even better a working solution ;-)

**Comment by jkasten80** [comment]
> Sorry, no green light yet but I made some progress. I'll give you an update within a week. Hopefully with at least a timeframe to finish it or even better a working solution ;-)

Did you find a solution?

**Comment by jkasten80** [comment]
@marcelveldt did you find a solution for this problem?

**Comment by marcelveldt** [comment]
Sorry for the late reply, I have been really busy in personal life due to some home renovation and a switch of jobs. The good news is that my new job is actually Nabu Casa so I'm sure I can squeeze in some time to fix this long standing issue.

I did have a look at this once and it was not as easy as my original thoughts so left it alone again.
So far my conclusion is that newer firmwares of the squeezebox hardware seem to rely on an alternative api with cometd streaming support so the solution is either to downgrade the firmware or maybe we should send some flag or something that we do not support cometd in this slimproto implementation

**Comment by jkasten80** [comment]
I am using the Squeezebox Radio with the community firmware. I am not sure it is using cometd or not.

**Comment by marcelveldt** [comment]
OK, thanks for the info. I really should get my hands on a real squeezebox device now because now I'm confused. I was testing with a soft squeeze player because my real SB Radio died.

I'm going to hunt Ebay if I can get my hands on a radio or Boom.

**Comment by marcelveldt** [comment]
So, I finally managed to get my hands on an actual SB Radio and prepared a fix.
This is just the basic fix so that the player will be discovered and can play music sent from HA. A nice follow up is that library consumers (e.g. Music Assistant) can utilize the cometd interface to actually show a menu structure on those players.
